### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by sandyis** [sagishporer/bulk-actions-for-paint-dot-net#1]
below exception in loading the plugin 
`
Type: PDNBulkUpdater.PDNBulkUpdaterEffect
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: This exception has been generated by the stub loader for PDNBulkUpdater. Please disregard.
   at PDNBulkUpdater.PDNBulkUpdaterEffect..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PaintDotNet.Menus.EffectMenuBase.AddEffectsToMenu() in D:\src\pdn\src\PaintDotNet\Menus\EffectMenuBase.cs:line 611
`

**Installation details**

`Application	paint.net 4.0.20 (Final 4.20.6579.36043)
Build Date	Friday, January 05, 2018
Install type	Classic
	`

**Comment by sagishporer** [comment]
If you've got this error in the "Settings" => "Plug-in Error" windows - this is how the plug-in works. Please check the "Edit" menu, at the bottom of the menu you should be able to see "Bulk Actions..." entry.

Why this is the case:
There is not way to add a menu entry not in the "Effects" menu (AFAIK) using a regular plug-in. To bypass this limitation the plug-in loads as an "Effect" plug-in, creates the menu entry in the "Edit" menu & crashes before creating the entry in the "Effects" menu.
