### ISSUE TITLE
NullReferenceException when trying to convert tga images

### ISSUE THREAD

**Issue by Arslet** [sagishporer/bulk-actions-for-paint-dot-net#2]
Hello, I am trying to convert some 24bit tga files to 32bit ones, and every time I try to convert any number of them I get this error:  
  
`System.NullReferenceException: Object reference not set to an instance of an object.
   at PaintDotNet.Data.InternalFileType.<>c__DisplayClass12_0.<FinalSave>b__0(Object sender, ProgressEventArgs e) in D:\src\pdn\src\PaintDotNet\Data\InternalFileType.cs:line 503
   at PaintDotNet.Data.TgaFileType.SaveTga(Surface input, Stream output, SavableBitDepths bitDepth, Boolean rleCompress, ProgressEventHandler progressCallback) in D:\src\pdn\src\PaintDotNet\Data\TgaFileType.cs:line 745
   at PaintDotNet.Data.TgaFileType.OnFinalSave(Document input, Stream output, Surface scratchSurface, Int32 ditherLevel, SavableBitDepths bitDepth, PropertyBasedSaveConfigToken token, ProgressEventHandler progressCallback) in D:\src\pdn\src\PaintDotNet\Data\TgaFileType.cs:line 691
   at PaintDotNet.Data.InternalFileType.FinalSave(Document input, Stream output, Surface scratchSurface, Int32 ditherLevel, Int32 threshold, SavableBitDepths bitDepth, PropertyBasedSaveConfigToken token, ProgressEventHandler progressCallback, Double progressStart, Double progressEnd) in D:\src\pdn\src\PaintDotNet\Data\InternalFileType.cs:line 506
   at PaintDotNet.Data.InternalFileType.OnSaveT(Document input, Stream output, PropertyBasedSaveConfigToken token, Surface scratchSurface, ProgressEventHandler progressCallback) in D:\src\pdn\src\PaintDotNet\Data\InternalFileType.cs:line 445
   at PaintDotNet.FileType.Save(Document input, Stream output, SaveConfigToken token, Surface scratchSurface, ProgressEventHandler callback, Boolean rememberToken) in D:\src\pdn\src\Data\FileType.cs:line 293
   at PDNBulkUpdater.OutputFile.Process(UpdateContext ctx, Dictionary`2 saveTokens, IProcessingEventListener events, Int32 index)
   at PDNBulkUpdater.Util.ProcessImages(UpdateContext ctx, Dictionary`2 saveTokens, IProcessingEventListener events)
`

I'm not sure what the problem is but I really like this and it seems it can be very useful for me, so I hope the issue is fixable.

**Comment by sagishporer** [comment]
Managed to reproduced. Converting any image to TGA fails.

**Comment by sagishporer** [comment]
Issue fixed in v0.3
